return {
    {
        title = "Recommend",
        build_list = {
            { request_tags = {},                title = "New",       subtitle = "", file = "recent" },
            { request_tags = { "order:score" }, title = "Top Score", subtitle = "", file = "highscore" },
        }
    },
    {
        title = "Artist",
        output_dir = "artist",
        build_list = {
            { one_tag = "anmi" },
            { one_tag = "ke-ta",                    title = "Ke-Ta" },
            { one_tag = "mivit" },
            { one_tag = "miyase_mahiro" },
            { one_tag = "natsumoka" },
            { one_tag = "annin_doufu" },
            { one_tag = "kino_(kino_konomi)" },
            { one_tag = "ryo" },
            { one_tag = "hiten_goane_ryu" },
            { one_tag = "fujisaki_hikari" },
            { one_tag = "higandgk" },
            { one_tag = "lium" },
            { one_tag = "dead_line" },
            { one_tag = "mayogii" },
            { one_tag = "dekitani" },
            { one_tag = "ogata_tei" },
            { one_tag = "kedama_milk" },
            { one_tag = "ayakura_juu" },
            { one_tag = "refeia" },
            { one_tag = "swordsouls" },
            { one_tag = "yoruneko" },
            { one_tag = "ru_zhai" },
            { one_tag = "criin_(659503)" },
            { one_tag = "wlop" },
            { one_tag = "cangkong" },
            { one_tag = "fufumi" },
            { one_tag = "inhoya2000" },
            { one_tag = "kuria_(clear_trip_second)" },
        }
    },
    {
        title = "Copyright",
        output_dir = "copyright",
        build_list = {
            { one_tag = "touhou" },
            { one_tag = "ookami_to_koushinryou" },
            { one_tag = "gochuumon_wa_usagi_desu_ka?",                 file = "gochuumon_wa_usagi_desu_ka" },
            { one_tag = "rokudenashi_majutsu_koushi_to_akashic_record" },
            { one_tag = "mahou_shoujo_madoka_magica" },
            { one_tag = "granblue_fantasy" },
            { one_tag = "arknights" },
            { one_tag = "sword_art_online" },
            { one_tag = "girls_frontline" },
            { one_tag = "azur_lane" },
            { one_tag = "princess_connect!" },
            { one_tag = "hyouka" },
            { one_tag = "blue_archive" },
            { request_tags = { "honkai:_star_rail" },                  title = "Nekopara Game CG",         file = "honkai_star_rail" },
            { request_tags = { "nekopara", "game_cg" },                title = "Nekopara Game CG",         file = "nekopara_gamecg" },
        }
    },
}
